from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from fastapi.responses import FileResponse, Response
from scanner import run_scan
import os
import tempfile
from datetime import datetime


app = FastAPI(title="PortScanner API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Request model ───────────────────────────────────────────────
class ScanRequest(BaseModel):
    target: str
    scan_type: str = "common"  # common | full

# ── Routes ──────────────────────────────────────────────────────
@app.get("/")
def root():
    return {"status": "PortScanner API is running ✅"}

@app.get("/health")
def health():
    return {"status": "ok"}

@app.post("/scan")
def scan(req: ScanRequest):
    target = req.target.strip()
    # Remove protocol if present
    target = target.replace("https://", "").replace("http://", "").split("/")[0]

    if not target:
        raise HTTPException(status_code=400, detail="Target is required")

    try:
        result = run_scan(target, req.scan_type)
        return result
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Scan failed: {str(e)}")


@app.post("/export-pdf")
def export_pdf(req: dict):
    try:
        data = req
        filename = f"scan_report_{data.get('ip','unknown')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(tempfile.gettempdir(), filename)

        doc = SimpleDocTemplate(filepath, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        story.append(Paragraph("🛡️ PortScanner Security Report", styles['Title']))
        story.append(Spacer(1, 12))

        # Summary
        story.append(Paragraph(f"Target: {data.get('target')} ({data.get('ip')})", styles['Normal']))
        story.append(Paragraph(f"Scan Date: {data.get('timestamp')}", styles['Normal']))
        story.append(Paragraph(f"Risk Rating: {data.get('risk_rating')} ({data.get('risk_score')}/100)", styles['Normal']))
        story.append(Paragraph(f"Open Ports: {data.get('open_ports_count')} found", styles['Normal']))
        story.append(Paragraph(f"Scan Duration: {data.get('scan_duration')}s", styles['Normal']))
        story.append(Spacer(1, 20))

        # Open Ports Table
        story.append(Paragraph("Open Ports", styles['Heading2']))
        story.append(Spacer(1, 8))

        table_data = [["Port", "Service", "Risk Level", "Details"]]
        for p in data.get('open_ports', []):
            table_data.append([
                str(p['port']),
                p['service'],
                p['risk_level'],
                p['risk_reason'][:60] + "..." if len(p['risk_reason']) > 60 else p['risk_reason']
            ])

        if len(table_data) > 1:
            t = Table(table_data, colWidths=[60, 80, 80, 280])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#7c5cfc')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('PADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(t)
        else:
            story.append(Paragraph("No open ports found.", styles['Normal']))

        story.append(Spacer(1, 20))

        # Recommendations
        story.append(Paragraph("Recommendations", styles['Heading2']))
        story.append(Spacer(1, 8))
        for rec in data.get('recommendations', []):
            story.append(Paragraph(f"• {rec}", styles['Normal']))
            story.append(Spacer(1, 4))

        story.append(Spacer(1, 20))
        story.append(Paragraph("Generated by PortScanner — Built by Keshav Kansara", styles['Normal']))

        doc.build(story)
        return FileResponse(filepath, media_type="application/pdf", filename=filename)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)